services:
  backend:
    build:
      context: ../server
    container_name: infracod-backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    command: sh -c "npx prisma migrate deploy && npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.infracod.com`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=cloudflare"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    networks:
      - infracod-net

  frontend:
    build:
      context: ../client
    container_name: infracod-frontend
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`panel.infracod.com`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls.certresolver=cloudflare"
      - "traefik.http.services.front.loadbalancer.server.port=80"
    networks:
      - infracod-net

networks:
  infracod-net:
    external: true
